name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy wheel
        sudo apt install portaudio19-dev
        sudo apt-get install libsndfile1
        pip install pesq pypesq
        pip install -r requirements.txt
        pip install -e .
        pip install pylint
        pip install Sphinx
        pip install sphinx_rtd_theme
    - name: Analysing the code with pylint
      run: |
        pylint DistantSpeech --disable=all --disable=unused-import
    - name: Unittests with pytest
      run: |
          pytest tests/unittests
    - name: Generate docs
      run: |
          cd docs
          sphinx-apidoc -o ./source ../DistantSpeech -f -e
          make html